version: "3.8"

name: "ansible-app"

services:
  ansible-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/:/src/
      - C:\Users\Sergey Rubtsov\.ssh:/root/.ssh